# Generated by Django 4.0.1 on 2022-06-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_category', models.CharField(max_length=50)),
                ('post_title', models.CharField(max_length=100)),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('post_img', models.ImageField(upload_to='picture/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
